import math
import time
import random
from pathlib import Path
from datetime import datetime

import requests
import pandas as pd
import geopandas as gpd
from pyproj import Transformer
from shapely.geometry import Point
from tqdm import tqdm


# CONFIGURATION
GOOGLE_API_KEY = open("src/gmap_api_key.txt", "r").read().strip()

# Output generated by 5-1-2_Find_road_no_GSV.py
GPKG_PATH = r"GSV_Downloader/roads_with_gsv.gpkg"

# Alternatively use the precomputed file supplied with the repository
# GPKG_PATH = r"src/HH-roads_NO_smoothness_HAS_gsv.gpkg"


LAYER_NAME = None

OSMID_COLUMN = "osm_id"


OUTPUT_DIR = Path("GSV_Downloader")
IMAGE_DIR = OUTPUT_DIR / "images"

LOG_FILE = OUTPUT_DIR / "streetview_buffer_log.csv"
LEGACY_LOG_FILE = OUTPUT_DIR / "streetview_log.csv"
IMAGE_REQUEST_USAGE_FILE = OUTPUT_DIR / "streetview_image_requests.csv"
COMPLETED_ROADS_FILE = OUTPUT_DIR / "completed_buffer_roads.csv"


# CRS
METRIC_CRS = "EPSG:25832"
WGS84_CRS = "EPSG:4326"

WGS84_TO_METRIC = Transformer.from_crs(
    WGS84_CRS,
    METRIC_CRS,
    always_xy=True,
)


# ROAD SELECTION
TARGET_ROAD_FEATURES = 2
ROAD_BUFFER_M = 10.0
SEARCH_POINT_SPACING_M = 5.0
GSV_SEARCH_RADIUS_M = 15

MONTHLY_IMAGE_REQUEST_LIMIT = 100

IMAGE_SIZE = "640x640"
FOV = 45
PITCH = -30

SLEEP_BETWEEN_IMAGE_REQUESTS = 0.15


def prepare_dirs():
    OUTPUT_DIR.mkdir(exist_ok=True)
    IMAGE_DIR.mkdir(exist_ok=True)


def read_csv_if_exists(path):
    if path.exists():
        try:
            return pd.read_csv(path)
        except pd.errors.EmptyDataError:
            return pd.DataFrame()
    return pd.DataFrame()


def save_log_row(row):
    df = pd.DataFrame([row])

    if LOG_FILE.exists():
        df.to_csv(
            LOG_FILE,
            mode="a",
            header=False,
            index=False,
        )
    else:
        df.to_csv(
            LOG_FILE,
            index=False,
        )


def save_usage_row(row):
    """
    Record an image API request before it is sent.

    This deliberately errs on the safe side: if the script crashes
    after this row is written but before Google receives the request,
    the request is still counted locally.
    """
    df = pd.DataFrame([row])

    if IMAGE_REQUEST_USAGE_FILE.exists():
        df.to_csv(
            IMAGE_REQUEST_USAGE_FILE,
            mode="a",
            header=False,
            index=False,
        )
    else:
        df.to_csv(
            IMAGE_REQUEST_USAGE_FILE,
            index=False,
        )


def clean_filename_value(value):
    return (
        str(value)
        .replace("/", "_")
        .replace("\\", "_")
        .replace(" ", "_")
        .replace(":", "_")
        .replace("?", "_")
        .replace("&", "_")
        .replace("=", "_")
    )


def count_rows_in_current_month(df, timestamp_column="timestamp"):
    if df.empty or timestamp_column not in df.columns:
        return 0

    timestamps = pd.to_datetime(
        df[timestamp_column],
        errors="coerce",
    )

    now = datetime.now()

    mask = (
        (timestamps.dt.year == now.year)
        & (timestamps.dt.month == now.month)
    )

    return int(mask.sum())


def count_legacy_image_requests_this_month():
    """
    Count image requests made by the OLD script this month.

    In the old log, only 'downloaded' and 'download_error' rows
    reached the Street View image endpoint. Metadata-only rows do
    not count here.
    """
    legacy_df = read_csv_if_exists(LEGACY_LOG_FILE)

    if legacy_df.empty:
        return 0

    required = {"timestamp", "status"}
    if not required.issubset(legacy_df.columns):
        return 0

    attempted = legacy_df[
        legacy_df["status"].isin(
            ["downloaded", "download_error"]
        )
    ].copy()

    return count_rows_in_current_month(attempted)


def count_new_image_requests_this_month():
    usage_df = read_csv_if_exists(IMAGE_REQUEST_USAGE_FILE)
    return count_rows_in_current_month(usage_df)


def get_monthly_request_count():
    return (
        count_legacy_image_requests_this_month()
        + count_new_image_requests_this_month()
    )


def record_image_request(osmid, pano_id, image_path):
    """
    Persist one request attempt before calling the image endpoint.
    """
    save_usage_row(
        {
            "timestamp": datetime.now().isoformat(timespec="seconds"),
            "osmid": osmid,
            "pano_id": pano_id,
            # Kept for CSV compatibility with earlier runs.
            "direction": "forward",
            "image_path": str(image_path),
        }
    )



def load_roads():
    if LAYER_NAME is None:
        roads = gpd.read_file(GPKG_PATH)
    else:
        roads = gpd.read_file(
            GPKG_PATH,
            layer=LAYER_NAME,
        )

    if roads.crs is None:
        raise ValueError("The GeoPackage has no CRS.")

    print("Available columns:")
    print(list(roads.columns))
    print()

    if OSMID_COLUMN not in roads.columns:
        raise ValueError(
            f"'{OSMID_COLUMN}' was not found. "
            f"Available columns are: {list(roads.columns)}"
        )

    roads = roads[
        roads.geometry.notna()
        & ~roads.geometry.is_empty
    ].copy()

    roads = roads[
        roads.geometry.geom_type.isin(
            ["LineString", "MultiLineString"]
        )
    ].copy()

    roads_metric = roads.to_crs(METRIC_CRS)

    roads_metric["length_m"] = roads_metric.geometry.length

    roads_metric = roads_metric[
        roads_metric["length_m"] > 1
    ].copy()

    print(f"Available road features: {len(roads_metric)}")
    print(
        f"Total road length: "
        f"{roads_metric['length_m'].sum() / 1000:.2f} km"
    )

    return roads_metric


def get_line_parts(geometry):
    """
    Return LineString components from LineString or MultiLineString.
    """
    if geometry.geom_type == "LineString":
        return [geometry]

    if geometry.geom_type == "MultiLineString":
        return list(geometry.geoms)

    return []


def calculate_heading_from_line(
    line,
    distance_along_line,
    step_m=3.0,
):
    """
    Calculate local road direction.

    0   = North
    90  = East
    180 = South
    270 = West
    """
    length = line.length

    d1 = max(0, distance_along_line - step_m)
    d2 = min(length, distance_along_line + step_m)

    p1 = line.interpolate(d1)
    p2 = line.interpolate(d2)

    dx = p2.x - p1.x
    dy = p2.y - p1.y

    if dx == 0 and dy == 0:
        return 0.0

    heading = math.degrees(math.atan2(dx, dy))
    return (heading + 360) % 360


def heading_at_nearest_position(road_geometry, point_metric):
    """
    Find the road part nearest to a panorama and calculate the
    road heading at the projected position on that part.
    """
    best_line = None
    best_distance = None
    best_along = None

    for line in get_line_parts(road_geometry):
        distance_to_line = line.distance(point_metric)

        if (
            best_distance is None
            or distance_to_line < best_distance
        ):
            best_line = line
            best_distance = distance_to_line
            best_along = line.project(point_metric)

    if best_line is None:
        return None

    return calculate_heading_from_line(
        best_line,
        best_along,
    )


def pano_point_to_metric(lat, lon):
    x, y = WGS84_TO_METRIC.transform(lon, lat)
    return Point(x, y)


def generate_search_points(
    road_geometry,
    spacing_m=SEARCH_POINT_SPACING_M,
):
    """
    Generate dense centerline query positions.

    Important:
    Google Street View metadata does not enumerate all panoramas
    in a polygon. Each query location returns a nearby/nearest
    panorama. Dense sampling plus pano-ID deduplication is therefore
    used to discover as many distinct panoramas as practical.
    """
    samples = []

    for part_number, line in enumerate(
        get_line_parts(road_geometry)
    ):
        length = line.length

        if length <= 1:
            continue

        if length <= spacing_m:
            distances = [length / 2]
        else:
            distances = []
            current_distance = spacing_m / 2

            while current_distance < length:
                distances.append(current_distance)
                current_distance += spacing_m

        for distance in distances:
            point_metric = line.interpolate(distance)

            point_wgs = (
                gpd.GeoSeries(
                    [point_metric],
                    crs=METRIC_CRS,
                )
                .to_crs(WGS84_CRS)
                .iloc[0]
            )

            samples.append(
                {
                    "part_number": part_number,
                    "distance_along_part_m": distance,
                    "lat": point_wgs.y,
                    "lon": point_wgs.x,
                }
            )

    return samples


def check_streetview_metadata(lat, lon):
    url = (
        "https://maps.googleapis.com/"
        "maps/api/streetview/metadata"
    )

    params = {
        "location": f"{lat},{lon}",
        "radius": GSV_SEARCH_RADIUS_M,
        "source": "outdoor",
        "key": GOOGLE_API_KEY,
    }

    try:
        response = requests.get(
            url,
            params=params,
            timeout=20,
        )
        response.raise_for_status()
        data = response.json()

    except Exception as e:
        return {
            "exists": False,
            "status": None,
            "pano_id": None,
            "pano_lat": None,
            "pano_lon": None,
            "pano_date": None,
            "copyright": None,
            "error": str(e),
        }

    status = data.get("status")

    if status != "OK":
        return {
            "exists": False,
            "status": status,
            "pano_id": None,
            "pano_lat": None,
            "pano_lon": None,
            "pano_date": None,
            "copyright": None,
            "error": None,
        }

    location = data.get("location", {})

    return {
        "exists": True,
        "status": status,
        "pano_id": data.get("pano_id"),
        "pano_lat": location.get("lat"),
        "pano_lon": location.get("lng"),
        "pano_date": data.get("date"),
        "copyright": data.get("copyright"),
        "error": None,
    }

def download_streetview_image(
    pano_id,
    heading,
    image_path,
):
    url = (
        "https://maps.googleapis.com/"
        "maps/api/streetview"
    )

    params = {
        "size": IMAGE_SIZE,
        "pano": pano_id,
        "heading": heading,
        "fov": FOV,
        "pitch": PITCH,
        "return_error_code": "true",
        "key": GOOGLE_API_KEY,
    }

    try:
        response = requests.get(
            url,
            params=params,
            timeout=30,
        )

        if response.status_code != 200:
            return False, f"HTTP {response.status_code}"

        content_type = response.headers.get(
            "Content-Type",
            "",
        )

        if "image" not in content_type:
            return (
                False,
                f"Response is not an image: {content_type}",
            )

        with open(image_path, "wb") as f:
            f.write(response.content)

        return True, None

    except Exception as e:
        return False, str(e)


def get_existing_downloaded_panos(osmid):
    """
    Read both the old and new logs so the new workflow does not
    download the same panorama again for the same OSM feature.
    """
    osmid_str = str(osmid)
    pano_ids = set()

    for path in [LEGACY_LOG_FILE, LOG_FILE]:
        df = read_csv_if_exists(path)

        if df.empty:
            continue

        required = {"osmid", "pano_id", "status"}
        if not required.issubset(df.columns):
            continue

        rows = df[
            (df["osmid"].astype(str) == osmid_str)
            & (df["status"] == "downloaded")
        ]

        pano_ids.update(
            rows["pano_id"]
            .dropna()
            .astype(str)
            .tolist()
        )

    return pano_ids


def get_completed_osmids():
    df = read_csv_if_exists(COMPLETED_ROADS_FILE)

    if df.empty or "osmid" not in df.columns:
        return set()

    return set(
        df["osmid"]
        .dropna()
        .astype(str)
    )


def mark_road_completed(osmid, road_index):
    row = pd.DataFrame(
        [
            {
                "timestamp": datetime.now().isoformat(
                    timespec="seconds"
                ),
                "road_index": road_index,
                "osmid": osmid,
            }
        ]
    )

    if COMPLETED_ROADS_FILE.exists():
        row.to_csv(
            COMPLETED_ROADS_FILE,
            mode="a",
            header=False,
            index=False,
        )
    else:
        row.to_csv(
            COMPLETED_ROADS_FILE,
            index=False,
        )


def process_road_feature(
    road,
    road_index,
    quota_state,
):
    """
    Search densely along one OSM road feature, accept only panorama
    camera locations within ROAD_BUFFER_M of the road geometry,
    and download one image per distinct panorama.

    Returns
    -------
    (new_successful_images, completed)
    """
    osmid = road[OSMID_COLUMN]
    osmid_clean = clean_filename_value(osmid)

    road_folder = IMAGE_DIR / osmid_clean
    road_folder.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()
    print(f"Processing OSM ID: {osmid}")
    print(f"Road length: {road['length_m']:.1f} m")
    print(f"Acceptance buffer: {ROAD_BUFFER_M:.1f} m")

    road_buffer = road.geometry.buffer(ROAD_BUFFER_M)

    sample_points = generate_search_points(
        road.geometry,
        SEARCH_POINT_SPACING_M,
    )

    print(
        f"Metadata search locations: "
        f"{len(sample_points)}"
    )


    existing_downloaded_panos = get_existing_downloaded_panos(
        osmid
    )

    encountered_pano_ids = set(existing_downloaded_panos)

    new_successful_images = 0
    new_image_attempts = 0

    for sample_number, sample in enumerate(
        sample_points,
        start=1,
    ):
        if quota_state["used"] >= MONTHLY_IMAGE_REQUEST_LIMIT:
            print(
                "Monthly local image-request limit reached "
                f"({quota_state['used']}/"
                f"{MONTHLY_IMAGE_REQUEST_LIMIT})."
            )
            return new_successful_images, False

        lat = sample["lat"]
        lon = sample["lon"]

        meta = check_streetview_metadata(
            lat,
            lon,
        )

        base_row = {
            "timestamp": datetime.now().isoformat(
                timespec="seconds"
            ),
            "road_index": road_index,
            "osmid": osmid,
            "road_length_m": road["length_m"],
            "buffer_m": ROAD_BUFFER_M,
            "search_spacing_m": SEARCH_POINT_SPACING_M,
            "search_radius_m": GSV_SEARCH_RADIUS_M,
            "sample_number": sample_number,
            "sample_lat": lat,
            "sample_lon": lon,
            "part_number": sample["part_number"],
            "distance_along_part_m": sample[
                "distance_along_part_m"
            ],
            "gsv_exists": meta["exists"],
            "gsv_status": meta["status"],
            "pano_id": meta["pano_id"],
            "pano_lat": meta["pano_lat"],
            "pano_lon": meta["pano_lon"],
            "pano_date": meta["pano_date"],
            "copyright": meta["copyright"],
            "distance_to_road_m": None,
            "inside_buffer": None,
            "heading": None,
            "direction": None,
            "image_path": None,
            "status": "started",
            "error": meta["error"],
        }

        if meta["error"]:
            base_row["status"] = "metadata_error"
            save_log_row(base_row)
            continue

        if not meta["exists"]:
            base_row["status"] = "no_streetview"
            save_log_row(base_row)
            continue

        if (
            meta["pano_lat"] is None
            or meta["pano_lon"] is None
        ):
            base_row["status"] = "missing_pano_coordinates"
            save_log_row(base_row)
            continue

        pano_point_metric = pano_point_to_metric(
            meta["pano_lat"],
            meta["pano_lon"],
        )

        distance_to_road = road.geometry.distance(
            pano_point_metric
        )

        inside_buffer = road_buffer.covers(
            pano_point_metric
        )

        base_row["distance_to_road_m"] = distance_to_road
        base_row["inside_buffer"] = inside_buffer

        if not inside_buffer:
            base_row["status"] = "outside_buffer"
            save_log_row(base_row)
            continue

        pano_id = str(meta["pano_id"])

        if pano_id in encountered_pano_ids:
            base_row["status"] = "duplicate_pano"
            save_log_row(base_row)
            continue

        encountered_pano_ids.add(pano_id)

        heading = heading_at_nearest_position(
            road.geometry,
            pano_point_metric,
        )

        if heading is None:
            base_row["status"] = "heading_error"
            save_log_row(base_row)
            continue

        if quota_state["used"] >= MONTHLY_IMAGE_REQUEST_LIMIT:
            print(
                "Monthly local image-request limit reached "
                f"({quota_state['used']}/"
                f"{MONTHLY_IMAGE_REQUEST_LIMIT})."
            )
            return new_successful_images, False

        pano_filename = clean_filename_value(pano_id)

        image_name = (
            f"{osmid_clean}_pano_{pano_filename}.jpg"
        )

        image_path = road_folder / image_name

        if image_path.exists():
            row = base_row.copy()
            row["heading"] = heading
            row["direction"] = "forward"
            row["image_path"] = str(image_path)
            row["status"] = "existing_file"
            save_log_row(row)
            continue

        record_image_request(
            osmid=osmid,
            pano_id=pano_id,
            image_path=image_path,
        )

        quota_state["used"] += 1
        new_image_attempts += 1

        ok, err = download_streetview_image(
            pano_id=pano_id,
            heading=heading,
            image_path=image_path,
        )

        row = base_row.copy()
        row["heading"] = heading
        row["direction"] = "forward"

        if ok:
            row["image_path"] = str(image_path)
            row["status"] = "downloaded"
            new_successful_images += 1
        else:
            row["status"] = "download_error"
            row["error"] = err

        save_log_row(row)

        print(
            f"  Image requests this month: "
            f"{quota_state['used']}/"
            f"{MONTHLY_IMAGE_REQUEST_LIMIT}",
            end="\r",
        )

        time.sleep(SLEEP_BETWEEN_IMAGE_REQUESTS)

    print()
    print(
        f"Downloaded {new_successful_images} new images "
        f"for OSM ID {osmid} "
        f"({new_image_attempts} new image requests)."
    )

    return new_successful_images, True


def main():
    prepare_dirs()

    roads = load_roads()

    monthly_used = get_monthly_request_count()

    print()
    print(
        "Local Street View image-request usage this month: "
        f"{monthly_used}/{MONTHLY_IMAGE_REQUEST_LIMIT}"
    )

    print(
        "Remaining local safety allowance: "
        f"{max(0, MONTHLY_IMAGE_REQUEST_LIMIT - monthly_used)}"
    )

    if monthly_used >= MONTHLY_IMAGE_REQUEST_LIMIT:
        print(
            "The monthly 9,500-request safety limit has already "
            "been reached. No image requests will be made."
        )
        return

    quota_state = {"used": monthly_used}

    completed_osmids = get_completed_osmids()

    available_roads = roads[
        ~roads[OSMID_COLUMN]
        .astype(str)
        .isin(completed_osmids)
    ].copy()

    if available_roads.empty:
        print(
            "No uncompleted road features remain for the "
            "buffer-based workflow."
        )
        return

    number_to_select = min(
        TARGET_ROAD_FEATURES,
        len(available_roads),
    )

    selected_indices = random.sample(
        available_roads.index.tolist(),
        number_to_select,
    )

    print()
    print(
        f"Randomly selected {number_to_select} "
        "road feature(s)."
    )

    for road_index in tqdm(
        selected_indices,
        desc="Processing road features",
    ):
        if quota_state["used"] >= MONTHLY_IMAGE_REQUEST_LIMIT:
            print()
            print(
                "Stopping because the monthly local image-request "
                "limit was reached."
            )
            break

        road = available_roads.loc[road_index]

        _, completed = process_road_feature(
            road,
            road_index,
            quota_state,
        )

        if completed:
            mark_road_completed(
                road[OSMID_COLUMN],
                road_index,
            )
        else:
            # Do not mark as completed. It can resume later.
            break

    print()
    print("Finished.")
    print(f"Image folder: {IMAGE_DIR}")
    print(f"Buffer log: {LOG_FILE}")
    print(f"Image-request tracker: {IMAGE_REQUEST_USAGE_FILE}")
    print(
        "Local image requests used this month: "
        f"{quota_state['used']}/"
        f"{MONTHLY_IMAGE_REQUEST_LIMIT}"
    )


if __name__ == "__main__":
    main()
